blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Support Question
    url: https://open.kakao.com/o/sTjHAUsf
    about: ê¶ê¸ˆí•˜ì‹  ì‚¬í•­ì„ ì˜¤í”ˆ ì¹´í†¡ì„ í†µí•´ ì‰½ê²Œ ë¬¸ì˜í•´ë³¼ ìˆ˜ ìˆì–´ìš”!
